In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import string

# let's keep our keras backend tensorflow quiet
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
# for testing on CPU
#os.environ['CUDA_VISIBLE_DEVICES'] = ''

# keras imports for the dataset and building our neural network
from keras.datasets import mnist
from keras.models import Sequential, load_model
from keras.layers.core import Dense, Dropout, Activation
from keras.models import Model
from keras.utils import np_utils

d:\product\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [16]:
csv_Train_File_Path = r'C:\Users\Sachin13390\Desktop\Kaggle-Emnist\train.csv'
csv_Test_File_Path = r'C:\Users\Sachin13390\Desktop\Kaggle-Emnist\test.csv'
csv_Submission_File_Path = 'My_Submission.csv'

model_File_Path = r'Keras_Numeric_Model.h5'

In [3]:
df = pd.read_csv(csv_Train_File_Path)

In [4]:
X = df.drop(df.columns[0],axis = 1)
y = df[df.columns[0]]

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [6]:
print("X_train shape", X_train.shape)
print("y_train shape", Y_train.shape)
print("X_test shape", X_test.shape)
print("y_test shape", Y_test.shape)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
# normalizing the data to help with the training
X_train /= 255
X_test /= 255

# print the final input shape ready for training
print("Train matrix shape", X_train.shape)
print("Test matrix shape", X_test.shape)

X_train shape (37800, 784)
y_train shape (37800,)
X_test shape (4200, 784)
y_test shape (4200,)
Train matrix shape (37800, 784)
Test matrix shape (4200, 784)


In [7]:
print(np.unique(Y_train, return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64), array([3724, 4213, 3757, 3845, 3675, 3456, 3735, 3963, 3660, 3772],
      dtype=int64))


In [8]:
n_classes = 10
print("Shape before one-hot encoding: ", Y_train.shape)

Shape before one-hot encoding:  (37800,)


In [9]:
Y_train = np_utils.to_categorical(Y_train, n_classes )
Y_test = np_utils.to_categorical(Y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

Shape after one-hot encoding:  (37800, 10)


In [13]:
model = Sequential()
model.add(Dense(784, input_shape=(784,)))
model.add(Activation('relu'))                            
model.add(Dropout(0.2))

model.add(Dense(1024))
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(10))
model.add(Activation('softmax'))

In [14]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [15]:
history = model.fit(X_train, Y_train,
          batch_size=128, epochs=20,
          verbose=2,
          validation_data=(X_test, Y_test))

Train on 37800 samples, validate on 4200 samples
Epoch 1/20
 - 13s - loss: 0.2669 - acc: 0.9187 - val_loss: 0.1491 - val_acc: 0.9524
Epoch 2/20
 - 12s - loss: 0.1041 - acc: 0.9679 - val_loss: 0.0965 - val_acc: 0.9705
Epoch 3/20
 - 12s - loss: 0.0723 - acc: 0.9778 - val_loss: 0.1042 - val_acc: 0.9700
Epoch 4/20
 - 12s - loss: 0.0569 - acc: 0.9813 - val_loss: 0.0956 - val_acc: 0.9695
Epoch 5/20
 - 12s - loss: 0.0435 - acc: 0.9854 - val_loss: 0.0996 - val_acc: 0.9736
Epoch 6/20
 - 13s - loss: 0.0349 - acc: 0.9892 - val_loss: 0.0917 - val_acc: 0.9771
Epoch 7/20
 - 12s - loss: 0.0378 - acc: 0.9876 - val_loss: 0.1183 - val_acc: 0.9690
Epoch 8/20
 - 12s - loss: 0.0271 - acc: 0.9910 - val_loss: 0.0930 - val_acc: 0.9774
Epoch 9/20
 - 12s - loss: 0.0260 - acc: 0.9913 - val_loss: 0.1117 - val_acc: 0.9752
Epoch 10/20
 - 12s - loss: 0.0267 - acc: 0.9912 - val_loss: 0.1013 - val_acc: 0.9767
Epoch 11/20
 - 13s - loss: 0.0224 - acc: 0.9928 - val_loss: 0.1167 - val_acc: 0.9736
Epoch 12/20
 - 12s - loss

In [17]:
model.save(model_File_Path)
KERAS_MODEL = load_model(model_File_Path)

In [23]:
data_frame = pd.read_csv(csv_Test_File_Path)
data_frame = data_frame / 255.0

In [24]:
print(type(data_frame.iloc[[1]]))

<class 'pandas.core.frame.DataFrame'>


In [25]:
output = []
for index in range(len(data_frame)):
    image = data_frame.iloc[[index]]
    image = image.reshape(1,784)
    
    label = KERAS_MODEL.predict_classes(image)
    
    print (label)
    
    

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [109]:
image = image/255

In [110]:
KERAS_MODEL.predict_classes(image.reshape(1,784))

array([22], dtype=int64)

In [111]:
listChar  = list(string.ascii_uppercase)

In [112]:
listChar[int(KERAS_MODEL.predict_classes(image.reshape(1,784)))]

'W'

In [113]:
print (KERAS_MODEL.predict_proba(image.reshape(1,784)))

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 4.0518877e-27 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 4.6068095e-28 1.4322576e-32 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  5.5319829e-34 0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]]


In [114]:
a= (KERAS_MODEL.predict_proba(image.reshape(1,784)))

In [115]:
print (type (a))
a


<class 'numpy.ndarray'>


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.0518877e-27,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.6068095e-28, 1.4322576e-32, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        5.5319829e-34, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [116]:
a[0,int(KERAS_MODEL.predict_classes(image.reshape(1,784)))]

1.0

In [96]:
print (prob[0,1])
print (type(prob[0,1]))
k = np.where(a == prob[0,1])
print ((k[1][0]))

0.2516576
<class 'numpy.float32'>
7
